### ISSUE TITLE
For contributors: Issues with Mocha tests: 

### ISSUE THREAD

**Issue by kaiyuan01** [LingDong-/wenyan-lang#407]
I cloned the project and tried to contribute more Mocha tests. I ran into the issues below when trying to run "hanzi2num.test.js" using /c/node-12.14.0-x64/**npm test** (gitbash in Windows 10). Any  suuggestions appreciated:

  

> 21 passing (16ms)
>   4 failing
> 
>   1) hanzi2num
>        hanzi2num("一沙一塵")
>          should translate hanzi to number correctly:
> 
>       AssertionError [ERR_ASSERTION]: 1.0001000000000005e-8 == 1.0001000000000008e-8
>       + expected - actual
> 
>       -1.0001000000000005e-8
>       +1.0001000000000008e-8
> 
>       at Context.<anonymous> (test\hanzi2num.test.js:62:14)
>       at Test.Runnable.run (node_modules\mocha-snapshots\src\index.js:19:22)
>       at processImmediate (internal/timers.js:439:21)
> 
>   2) hanzi2num
>        hanzi2num("無量大數")
>          should translate hanzi to number correctly:
> 
>       AssertionError [ERR_ASSERTION]: 1e+68 == 1.0000000000000002e+68
>       + expected - actual
> 
>       -1e+68
>       +1.0000000000000002e+68
> 
>       at Context.<anonymous> (test\hanzi2num.test.js:79:14)
>       at Test.Runnable.run (node_modules\mocha-snapshots\src\index.js:19:22)
>       at processImmediate (internal/timers.js:439:21)
> 
>   3) hanzi2num
>        hanzi2num("三千萬埃")
>          should translate hanzi to number correctly:
> 
>       AssertionError [ERR_ASSERTION]: 2.9990000000000017e-13 == 2.9990000000000027e-13
>       + expected - actual
> 
>       -2.9990000000000017e-13
>       +2.9990000000000027e-13
> 
>       at Context.<anonymous> (test\hanzi2num.test.js:106:14)
>       at Test.Runnable.run (node_modules\mocha-snapshots\src\index.js:19:22)
>       at processImmediate (internal/timers.js:439:21)
> 
>   4) hanzi2num
>        hanzi2num("不可思議")
>          should translate hanzi to number correctly:
> 
>       AssertionError [ERR_ASSERTION]: 1e+64 == 1.0000000000000002e+64
>       + expected - actual
> 
>       -1e+64
>       +1.0000000000000002e+64
> 
>       at Context.<anonymous> (test\hanzi2num.test.js:118:14)
>       at Test.Runnable.run (node_modules\mocha-snapshots\src\index.js:19:22)
>       at processImmediate (internal/timers.js:439:21)
> 
> 
> 
> npm ERR! Test failed.  See above for more details.
>

**Comment by antfu** [comment]
Yes. This problem is reproducible. Depends on what OS and CPU Arch you use, the `console.log` for floating number may resulting different outputs. The snapshot is matched to Ubuntu, in order to passes CI. But it will fail on some Windows. 

I don't have a proper solution for this currently. Feel free to leave any suggestions. Thanks.

**Comment by kaiyuan01** [comment]
@antfu Thanks for the quick response. I also have issues with 


$ /c/node-12.14.0-x64/npm install --save-dev -g fs-extra
+ fs-extra@8.1.0
updated 1 package in 0.857s

$ /c/node-12.14.0-x64/npm test

> wenyanlang@0.1.1 test ~\git\sandbox\wenyan-lang_FORK
> mocha --require mocha-snapshots

C:\node-12.14.0-x64\node_modules\mocha\node_modules\yargs\yargs.js:1163
      else throw err
           ^

Error: Cannot find module 'fs-extra'
Require stack:
- ~\git\sandbox\wenyan-lang_FORK\test\examples.test.js
- C:\node-12.14.0-x64\node_modules\mocha\lib\mocha.js
- C:\node-12.14.0-x64\node_modules\mocha\lib\cli\one-and-dones.js
- C:\node-12.14.0-x64\node_modules\mocha\lib\cli\options.js
- C:\node-12.14.0-x64\node_modules\mocha\bin\mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (~\git\sandbox\wenyan-lang_FORK\test\examples.test.js:1:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at C:\node-12.14.0-x64\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\node-12.14.0-x64\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\node-12.14.0-x64\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\node-12.14.0-x64\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\node-12.14.0-x64\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\node-12.14.0-x64\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\node-12.14.0-x64\node_modules\mocha\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\node-12.14.0-x64\node_modules\mocha\node_modules\yargs\yargs.js:1104:24)
    at Object.parse (C:\node-12.14.0-x64\node_modules\mocha\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\node-12.14.0-x64\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\node-12.14.0-x64\node_modules\mocha\bin\mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...\\git\\sandbox\\wenyan-lang_FORK\\test\\examples.test.js',
    'C:\\node-12.14.0-x64\\node_modules\\mocha\\lib\\mocha.js',
    'C:\\node-12.14.0-x64\\node_modules\\mocha\\lib\\cli\\one-and-dones.js',
    'C:\\node-12.14.0-x64\\node_modules\\mocha\\lib\\cli\\options.js',
    'C:\\node-12.14.0-x64\\node_modules\\mocha\\bin\\mocha'
  ]
}
npm ERR! Test failed.  See above for more details.

**Comment by antfu** [comment]
@kaiyuan01 
I think you should try `npm i -D fs-extra` without `-g` flag
