### ISSUE TITLE
For contributors: npm test gave: Error: Cannot find module '../dist/core/index.min.js'

### ISSUE THREAD

**Issue by kaiyuan01** [LingDong-/wenyan-lang#408]
npm test threw the following error: (see below) Any local set up required in order to run npm mocha tests? BYW, do we have a chat/forum just for contributors?

> wenyanlang@0.1.1 test 

> mocha --require mocha-snapshots

...\git\sandbox\wenyan-lang_FORK\node_modules\yargs\yargs.js:1163
      else throw err
           ^

Error: Cannot find module '../dist/core/index.min.js'

**Comment by antfu** [comment]
@kaiyuan01 for running test, you should run `npm run build` first. I will update the testing document. Thanks!

> BTW, do we have a chat/forum just for contributors?

For now, I don't think we have one. Maybe we can just use Github at this moment. 😉 @LingDong-  how do you think?

**Comment by kaiyuan01** [comment]
@antfu "npm install @wenyanlang/core" and "npm run build" did the trick. However, still got 14 test failures, not sure if it is related to Windows/gitbash: (showing only one failure example below)

 49 passing (40s)
  14 failing

  1) examples
       javascript
         collatz:
     Error: Snapshot didn't match

  - "[ 12, 6, 3, 10, 5, 16, 8, 4, 2, 1, 1 ]\n[ 19, 58, 29, 88, 44, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1, 1 ]\n[ 27,\n  82,\n  41,\n  124,\n  62,\n  31,\n  94,\n  47,\n  142,\n  71,\n  214,\n  107,\n  322,\n  161,\n  484,\n  242,\n  121,\n  364,\n  182,\n  91,\n  274,\n  137,\n  412,\n  206,\n  103,\n  310,\n  155,\n  466,\n  233,\n  700,\n  350,\n  175,\n  526,\n  263,\n  790,\n  395,\n  1186,\n  593,\n  1780,\n  890,\n  445,\n  1336,\n  668,\n  334,\n  167,\n  502,\n  251,\n  754,\n  377,\n  1132,\n  566,\n  283,\n  850,\n  425,\n  1276,\n  638,\n  319,\n  958,\n  479,\n  1438,\n  719,\n  2158,\n  1079,\n  3238,\n  1619,\n  4858,\n  2429,\n  7288,\n  3644,\n  1822,\n  911,\n  2734,\n  1367,\n  4102,\n  2051,\n  6154,\n  3077,\n  9232,\n  4616,\n  2308,\n  1154,\n  577,\n  1732,\n  866,\n  433,\n  1300,\n  650,\n  325,\n  976,\n  488,\n  244,\n  122,\n  61,\n  184,\n  92,\n  46,\n  23,\n  70,\n  35,\n  106,\n  ... 13 more items ]\n"
  + "[\n  12, 6, 3, 10, 5,\n  16, 8, 4,  2, 1,\n   1\n]\n[\n  19, 58, 29, 88, 44, 22, 11,\n  34, 17, 52, 26, 13, 40, 20,\n  10,  5, 16,  8,  4,  2,  1,\n   1\n]\n[\n    27,   82,   41,  124,   62,   31,   94,   47,  142,   71,  214,\n   107,  322,  161,  484,  242,  121,  364,  182,   91,  274,  137,\n   412,  206,  103,  310,  155,  466,  233,  700,  350,  175,  526,\n   263,  790,  395, 1186,  593, 1780,  890,  445, 1336,  668,  334,\n   167,  502,  251,  754,  377, 1132,  566,  283,  850,  425, 1276,\n   638,  319,  958,  479, 1438,  719, 2158, 1079, 3238, 1619, 4858,\n  2429, 7288, 3644, 1822,  911, 2734, 1367, 4102, 2051, 6154, 3077,\n  9232, 4616, 2308, 1154,  577, 1732,  866,  433, 1300,  650,  325,\n   976,  488,  244,  122,   61,  184,   92,   46,   23,   70,   35,\n   106,\n  ... 13 more items\n]\n"

      at module.exports (node_modules\mocha-snapshots\src\matchSnapshot.js:34:13)
      at Proxy.<anonymous> (node_modules\mocha-snapshots\src\index.js:24:3)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at runExample (test\examples.test.js:50:23)
      at Context.<anonymous> (test\examples.test.js:57:24)
      at Test.Runnable.run (node_modules\mocha-snapshots\src\index.js:19:22)
      at processImmediate (internal/timers.js:439:21)

**Comment by antfu** [comment]
Sorry I am not familiar with git-bash stuff. But Powershell on Window works fine for me. Maybe this is an output problem from git-bash?

**Comment by kaiyuan01** [comment]
Thanks @antfu . Somehow I still got this error even after I ran it in PowerShell on Win 10:

Error: Invalid Chai property: matchSnapshot

Any more suggestions for this error?

**Comment by antfu** [comment]
@kaiyuan01  `matchSnapshot` is provided by `mocha-snapshots` package. Looks like you have missed the dependencies or somehow.
