### ISSUE TITLE
For contributors: cannot import (require) lib from mocha test file: unexpected token

### ISSUE THREAD

**Issue by kaiyuan01** [LingDong-/wenyan-lang#477]
I am trying to import and write test cases for 列經:

var {  遍施 } = **require**('../lib//列經.wy');

It failed while running "rpm -t" as import (require) failed:

\wenyan-lang\lib\算經.wy:1
吾有一數。名之曰「假圓周率」。

**SyntaxError: Invalid or unexpected token**
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (...\git\sandbox\wenyan-lang\test\列經.test2.js:2:46)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)

This is preventing me from writing test cases to cover libraries. Any thoughts?

**Comment by kaiyuan01** [comment]
Maybe I have to do it this way:

> require("../dist/core/index.min");

**Comment by LingDong-** [comment]
Hi @kaiyuan01 ,

Your first method wouldn't work because you're importing a wenyan file in node.js, who obviously does not understand it. (I hope one day it does :)

Before you start, I'd advise you read [Testing.md](https://github.com/LingDong-/wenyanlang/blob/master/documentation/) first. In fact, please learn about JavaScript in general. Here are some great resources:

https://www.w3schools.com/nodejs/
https://developer.mozilla.org/en-US/docs/Web/JavaScript
