### ISSUE TITLE
SyntaxError is thrown when using the command `wenyan`

### ISSUE THREAD

**Issue by UlyssesZh** [LingDong-/wenyan-lang#479]
Here are the error messages.
```
$ wenyan -v
/home/ulysses/.nvm/versions/io.js/v3.3.1/lib/node_modules/@wenyanlang/cli/index.min.js:251
    let result = [{ type: eTokenType.BEGIN }];
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:951:3
```
Here is info of my computer.
```
$ uname -a
Linux ulysses-ubuntu 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ node -v
v3.3.1
```
```
$ npm -v
2.14.3
```
```
$ iojs -v
v3.3.1
```

**Comment by kaiyuan01** [comment]
I had the similar issue before. The old version of node js package was the culprit...  I've updated to v12 and it's working.

We need to add min version of node on readme if it's not there.

**Comment by kaiyuan01** [comment]
Mine:

 node -v
v12.14.0

Your version is v3 - that's way too old

**Comment by UlyssesZh** [comment]
> Mine:
> 
> node -v
> v12.14.0
> 
> Your version is v3 ?? - that's way too old

I switched to use node v13.5.0, and it worked. Thanks.
