### ISSUE TITLE
Cannot make「言序數」function work

### ISSUE THREAD

**Issue by kaiyuan01** [LingDong-/wenyan-lang#488]
## Describe your issue/suggestions
The following snippet did not work somehow, any thoughts?

吾嘗觀「「曆法」」之書。方悟「言序數」之義。

施「言序數」於十。書之。

I did not see anything came out either, at https://wenyan-snippets.glitch.me/api?id=23, or http://wenyan-lang.lingdong.works/ide.html

## Checklist

Before you create this issue, Please make sure ALL the following items are checked

- [ ] If this is a feature request, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#feature-requests)
- [x] If this is a bug report, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#known-bugs)

**Comment by kaiyuan01** [comment]
My local runtime threw:

 calendar:
     TypeError: 言序數 is not a function
      at eval (eval at <anonymous> (src/parser.js:826:9), <anonymous>:1:49636)
      at /workspace/wenyan-lang/src/parser.js:826:9
      at evalCompiled (src/parser.js:833:5)
      at runExample (test/examples.calendar.test.js:55:3)
      at Context.it (test/examples.calendar.test.js:75:24)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)

  2) examples
       romanizeIdentifiers
         calendar:
     TypeError: YAN2XU4SHU4 is not a function
      at eval (eval at <anonymous> (src/parser.js:826:9), <anonymous>:1:65749)
      at /workspace/wenyan-lang/src/parser.js:826:9
      at evalCompiled (src/parser.js:833:5)
      at runExample (test/examples.calendar.test.js:55:3)
      at Context.it (test/examples.calendar.test.js:75:24)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)

**Comment by kaiyuan01** [comment]
Similar errors can be found here for function '言百內數': https://github.com/LingDong-/wenyan-lang/pull/487

**Comment by statementreply** [comment]
These are internal functions not exported from the module (`吾有一術`), so they can't be imported with `吾嘗觀...之書。方悟...之義。`.

**Comment by kaiyuan01** [comment]
My bad, I missed that. Thanks.
