### ISSUE TITLE
改了 lib/ 目录内 stdlib 库文件，要重新 build 才生效吗？

### ISSUE THREAD

**Issue by lymslive** [LingDong-/wenyan-lang#514]
发现`lib/列经`中有关“排序”的实现，那递归的两行应该是从 example 中 copy 过来的，还是“快排”，应该是“排序”吧。
但是我尝试本地改成“排序”，再运行一个测试用例时，仍报错“快排”未定义。

**Comment by antfu** [comment]
Yes. Stdlib is bundled into the compiled js file. You should rebuild to make it work.

**Comment by antfu** [comment]
If you do not want to rebuild repeatedly, there is a continuous building mode for you
```bash
npm run dev
```

**Comment by lymslive** [comment]
列经好像还是有问题，我重新 build 之后，报另一个错了：

```
TypeError: 首.concat is not a function
    at eval (eval at <anonymous> (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:1840:9), <anonymous>:1:1103)
    at eval (eval at <anonymous> (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:1840:9), <anonymous>:1:2243)
    at /home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:1840:9
    at evalCompiled (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:1847:5)
    at exec (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:2240:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

简单的测试代码：
```
吾嘗觀『列經』之書。方悟「排序」之義。

吾有一術。名之曰「数序」。欲行是術。必先得二數。曰「甲」曰「乙」乃行是術曰。
        減「甲」以「乙」乃得其
是謂「数序」之術也。

施「数序」於一於二。書之。
施「数序」於二於一。書之。

吾有一列。名之曰「己」。
充「己」以五。以三。以二十。以八。以三十五。以七百。
施「排序」於「数序」於「己」。書之。
```

**Comment by antfu** [comment]
Thanks for the feedback! I have made a fix. Please now use:

```
吾嘗觀『列經』之書。方悟「排序」之義。

充「己」以五。以三。以二十。以八。以三十五。以七百。
施「排序」於「己」。書之。
```
